name: test

on:
  pull_request:
    branches: [ "main" ]

permissions: {} # lock everything by default (least-privilege)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    permissions:
      contents: read
    strategy:
      matrix:
        test: [asm-bench,asm-racer,asm-util,asm-unit,corset-bench,corset-racer,corset-test,unit-test]
        field: [BLS12_377,KOALABEAR_16,GF_8209]
        exclude:
          - { field: KOALABEAR_16, test: asm-racer }
          - { field: KOALABEAR_16, test: corset-racer }
          - { field: KOALABEAR_16, test: unit-test }
          - { field: GF_8209,      test: asm-bench }
          - { field: GF_8209,      test: asm-racer }
          - { field: GF_8209,      test: asm-util }
          - { field: GF_8209,      test: corset-bench }
          - { field: GF_8209,      test: corset-racer }
          - { field: GF_8209,      test: unit-test }
      fail-fast: false
    runs-on: gha-runner-scale-set-ubuntu-24-amd64-large
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 #v6.2.0
        with:
          go-version: '>=1.24'
      - run: make ${{ matrix.test }}
        env:
          GOMAXPROCS: 8
          GOMEMLIMIT: 16GiB
          GOCORSET_FIELD: ${{ matrix.field }}
